apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: details
  name: details
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: details
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: details
    spec:
      containers:
        - image: g33/details
          name: g33-details
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
