apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: reviews
  name: reviews
spec:
  ports:
    - name: "7080"
      port: 7080
      targetPort: 7080
  selector:
    io.kompose.service: reviews
status:
  loadBalancer: {}
